name:                battlegrounds
version:             0.1.0.0
github:              "blastwind/battlegrounds"
license:             BSD-3-Clause
author:              "Andrew Chen"
maintainer:          "andrewchen14250@gmail.com"
copyright:           "2024 Andrew Chen"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/battlegrounds#readme>

dependencies:
- base >= 4.7 && < 5



ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - mtl == 2.3.1
  - containers == 0.6.7
  - random == 1.2.1.2
  - MonadRandom
  - parsec
  - pretty-simple
  - text == 2.0.2
  - large-generics == 0.2.2
  - large-records == 0.4.1
  - record-hasfield


executables:
  battlegrounds-terminal:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - battlegrounds


tests:
  battlegrounds-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - battlegrounds
    # - containers == 0.6.7
    - tasty
    - tasty-hunit
    - large-generics == 0.2.2
    - large-records == 0.4.1
    - record-hasfield